; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:over_STLink]
platform = ststm32
board = bluepill_f103c8_128k
framework = arduino
monitor_parity = E
lib_deps = 
	Wire
	SPI
	arduino-libraries/SD@^1.3.0
monitor_speed = 115200
build_flags = -Wall -Wparentheses -fexceptions -Wdeprecated-declarations
upload_protocol = stlink
; board_upload.offset_address = 0x08000D00
upload_flags = -c set CPUTAPID 0x2ba01477
build_src_filter=
	+<**/*.c>
	+<**/*.cpp>
	-<**/*-except.cpp>
	-<**/*-dnc.cpp>


[platformio]
description = Взлёт 2024/25
name = Banana-MMM
default_envs = over_STLink
